name: CI on PR to dev

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      # Supabase connection string (add in GitHub repo settings → Secrets → Actions)
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DAGSHUB_USER_TOKEN: ${{ 33444754da27d64f321469adb43a75ef48957dbd }}
      MLFLOW_TRACKING_USERNAME: Sukaina22
      MLFLOW_TRACKING_PASSWORD: ${{ 33444754da27d64f321469adb43a75ef48957dbd }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Backend (FastAPI) ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          pytest tests/integration

      # ---------- Frontend (Next.js) ----------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend deps
        working-directory: ui
        run: npm ci

      - name: Build frontend
        working-directory: ui
        run: npm run build
